name: java-docker-release
on:
  workflow_call:
    inputs:
      github_repository:
        description: "Default Github environment variable - repository"
        required: true
        type: string          
      docker_context:
        description: "Specifies the base directory for Docker image building"
        default: "."
        required: false
        type: string
      docker_file_name:
        description: "Specifies the path to the Dockerfile used in the image building process"
        default: "./Dockerfile"
        required: false
        type: string     
      os_version:
        description: "Container operating system"
        default: "ubuntu-latest"
        required: false
        type: string
    secrets:
      DOCKER_REGISTRY_URL:
        required: true
      DOCKER_REGISTRY_USERNAME:
        required: true
      DOCKER_REGISTRY_TOKEN:
        required: true        
jobs:
  build-and-push:
    runs-on: ${{ inputs.os_version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Set up Qemu
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
          
      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v6
      #   with:
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max
      #     context: ${{ inputs.docker_context }}
      #     platforms: linux/amd64,linux/arm64
      #     push: ${{ github.ref_type == 'tag' }}
      #     tags: ${{ steps.metadata.outputs.tags }}
      #     labels: ${{ steps.metadata.outputs.labels }}
      #     provenance: mode=max
      #     sbom: true          